video_path: data/dance/videos/dance-jump.mp4
save_dir: outputs/dance/ddim_latents
max_number_of_frames: 49

n_timesteps: 999
prompt: Amazing quality, masterpiece, A woman is dancing.
negative_prompt: ""
save_ddim_reconstruction: True